### PR TITLE
Added: example datasets + rworkflows + CRAN/Bioc-compatibility

### PR DESCRIPTION
**Pull request by bschilder**
Hi there!, 

Really excited to use `SCAVENGE` in our work as it seems to have some really nice features.

In the interest of making it more user-friendly and robust across platforms, I've gone through and tried to make as much of the code/documentation CRAN/Bioc-compatible. I've also added my `rworkflows` GitHub Actions workflow so that it automatically runs checks, builds the docs site, and pushes a container to Dockerhub every time you push changes to GitHub. See here to read more:
https://github.com/neurogenomics/rworkflows/

I've gotten it to the point where it's passing all CRAN checks on Linux and Mac. Still trying to figure out the issues with Windows (might be related to size limits on their Virtual Machines).
https://github.com/neurogenomics/SCAVENGE/actions/runs/3639942791

A couple remaining points of improvement that would be great if you could work on:
- [ ] Go through the examples I created and make sure they're doing what you expect.
- [ ] Add `DOCKER_TOKEN` and `PAT_GITHUB` as GitHub Secrets in your repo.
- [ ] Update the *docker.Rmd* vignette and *.github/workflows/rworkflows.yml* files with your Dockerhub username and/or organization name. 
- [ ] Reduce the total package size to <5Mb. Currently, the "pbmc5k_SE.rda" data alone is 36.2Mb. Distributing large datasets with the package slows the whole thing down and causes issues with CRAN/Bioc submission. Once useful option might be to transition to using data from the [`scRNAseq`](https://bioconductor.org/packages/release/data/experiment/html/scRNAseq.html) package, which downloads and caches datasets from Bioc servers. They have several PBMC datasets you can choose from.

Bonus points if you can add the following
- [ ] Add unit tests with the `testthat` package (not required by CRAN/Bioc but is a really great way of making sure your functions consistently run as expected).

For more details, I've documented all the changes in the *NEWS.md* file:
https://github.com/neurogenomics/SCAVENGE/blob/main/NEWS.md

Just let me know if you have any questions in the meantime! 

Best, 
Brian Schilder

### CODE REVIEW

**Comment by fl-yu** [comment]
Wow!!  Brian, thank you so much for your kindness and great effort for updatiing SCAVENGE package. I just went through changes and it looks great to me!
For your suggestions, I will go through the example and tutorial later on and docker things (I will follow up how to use docker as currently I did not have a chance to use it). Regarding another good suggesiton is about example data from `scRNAseq` package, I am not sure if they collect scATAC-seq data.

Again, thank you so mcuh for your important contribution!!

**Comment by bschilder** [comment]
> Wow!! Brian, thank you so much for your kindness and great effort for updatiing SCAVENGE package. I just went through changes and it looks great to me! 

No problem, glad to help 😃 

> For your suggestions, I will go through the example and tutorial later on and docker things (I will follow up how to use docker as currently I did not have a chance to use it). 

>Regarding another good suggesiton is about example data from `scRNAseq` package, I am not sure if they collect scATAC-seq data.

Woops, my bad! You're totally right, wrong assay type. But I think there should be some equivalent packages for scATAC-seq. Here's one that might work:
https://bioconductor.org/packages/release/data/experiment/html/scATAC.Explorer.html

**Review by fl-yu — APPROVED** [review]

**Comment by fl-yu** [comment]
Hi Brian, I got in a trouble when I tried to push the commit to resolve confilcts. Do you have any idea for this? Thank you! 

image
image

**Review by fl-yu — APPROVED** [review]

**Comment by bschilder** [comment]
> Hi Brian, I got in a trouble when I tried to push the commit to resolve confilcts. Do you have any idea for this? Thank you!
> 
> image image

I think it was just some conflicts in the README text. Just went through and resolved those manually. But please do double check it to see if I missed anything.

**Comment by bschilder** [comment]
yay! thanks @fl-yu  🎆 

One minor thing I just noticed in the README:
> Once all of the dependencies for SCAVENGE are installed, the package can be installed directly from GitHub by typing the following into an R console:
> ...

Can be changed to :
> SCAVENGE can be installed directly from GitHub by typing the following into an R console:
> ...

because all dependencies should be installed automatically with the changes i made to the DESCRIPTION file.

If you could update this whenever you make your next push, that would be great! For minor changes like this, you can skip the `rworkflows` action by adding "[skip ci]" somewhere in the commit message.

**Comment by bschilder** [comment]
Oh also, you'll need to add your GitHub token as a GitHub Secret named `PAT_GITHUB` in this repo. This gets around the GH download limits (which is why `rworkflows` is failing right now) and allows it to push to the gh-pages branch.

Also, if you want to deploy a containerised version of SCAVENGE to DockerHub you'll need to:
1.  make a DockerHub account (if you don't already have one) and create a token.
2. add the token as another GH Secret named `DOCKER_TOKEN`
3. change `docker_user` and `docker_org` to your username (and DockerHub org name, if you're part of one. otherwise it can just be the same as your username).
https://github.com/sankaranlab/SCAVENGE/blob/main/.github/workflows/rworkflows.yml

Once you've done these, `rworkflows` should work smoothly.

**Comment by fl-yu** [comment]
Hi Brain, I have set up the token and modified docker_user and org as indicated, however, rworkflows still can not work. I leave the `value` section blank, is this setting correct? Do you have any thoughts on this? Thank you!!! 
image
image

**Comment by bschilder** [comment]
> Hi Brian, I have set up the tokens and modified docker_user and org as indicated, however, rworkflows still can not work. I leave the `value` section blank, is this setting correct? Do you have any thoughts on this? Thank you!!! image image

Did you initially set the values to the token values? See here for more instructions.
https://github.com/neurogenomics/templateR#github-secrets

PS - just make you don't post any screenshots of the token itself here, that's a major security risk

**Comment by fl-yu** [comment]
Thank you for the reminder! I just set two tokens of `PAT_GITHUB` and `DOCKER_TOKEN` under my account and passed values to the tokens in the Actions secret as I posted. However, it fails again...
[logs_5.zip](https://github.com/sankaranlab/SCAVENGE/files/10320745/logs_5.zip)

**Comment by bschilder** [comment]
Ok, thanks for setting that up @bschilder !

It seems the `r-lib/action` action I'm using in `rworkflows` is having issues installing remote R packages from GitHub. I've filed an issue with them and will continue troubleshooting this in the meantime. I'll keep you posted as soon as I figure this out!
https://github.com/r-lib/actions/issues/674

**Comment by fl-yu** [comment]
Does it seem to be a permission issue? Do you have any sense of how I should set the access for each token?

**Comment by bschilder** [comment]
> Does it seem to be a permission issue? Do you have any sense of how I should set the access for each token?

Quite possibly, make sure both tokens have cloning and push permissions.

**Comment by fl-yu** [comment]
Hi Brian, I just granted all the permissions for these two tokens and the action still does not work.

**Here are my tokens (without value):**
image
image

**Here is the yaml file where I have replace with my docker account:**
https://github.com/sankaranlab/SCAVENGE/blob/main/.github/workflows/rworkflows.yml

**Here is the error of actions:**
image
image

 Do you have any idea about these? I wonder if there is any chance you can help to set up this directly? Thank you so much!!!

**Comment by bschilder** [comment]
I've not seen the feature "Fine-grained tokens" before, so I think what I've use would be "Tokens (classic)". This might also help avoid the future issue of the token expiring soon (Feb or March 2023, in your case).

Sure, I think this is getting rather tricky so if you make me a collaborator on the `SCAVENGE` repo I can try and figure this out.

**Comment by fl-yu** [comment]
Awesome!! Please let me know if anything I can do, thank you so much for your help!!

**Comment by bschilder** [comment]
Cool, thanks @fl-yu !
I've got everything passing on my fork and will merge it with the main one:
https://github.com/neurogenomics/SCAVENGE

Also, would you alright with me adding my name as a contributor to the *DESCRIPTION* file?

**Comment by fl-yu** [comment]
Great! Definitely, you contributed to this update a lot and  I am happy to add you as a contributor! Please feel free to do so! Thanks @bschilder !

**Pull request merged**
